(function(g){var window=this;var W4=function(a,b,c){var d=b.xa();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.xc(c?c:"mqdefault.jpg");var f=b instanceof g.ZA&&b.lengthSeconds?g.UL(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.RD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.ZA?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Vj||g.DM("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",
{TITLE:b.title}),duration:f,url:b.Eh(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.TD&&(d.playlist_length=b.getLength());a.update(d)},X4=function(a){g.U.call(this,{D:"div",
W:["ytp-upnext","ytp-player-content"],M:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",V:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{D:"span",I:"ytp-upnext-title",V:"{{title}}"},{D:"span",I:"ytp-upnext-author",V:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",M:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
K:[{D:"svg",M:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",I:"ytp-svg-autoplay-circle",M:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",M:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",M:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",
K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",V:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.U({D:"button",W:["ytp-upnext-cancel-button","ytp-button"],M:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
V:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.B(this,this.B);this.B.ha("click",this.eK,this);this.B.ca(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.I(this.Jm,5E3,this);g.B(this,this.G);this.H=0;this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.OL);this.Uz();this.L(a,"autonavvisibility",this.Uz);this.L(a,"mdxnowautoplaying",this.gL);this.L(a,"mdxautoplaycanceled",this.hL);this.L(a,"mdxautoplayupnext",this.oC);3==this.u.getPresentingPlayerType()&&
(a=(a=g.nL(g.fL(this.u)))?a.HE():null)&&this.oC(a);g.K(this.element,"ytp-upnext-mobile",this.u.O().o)},Y4=function(a,b){if(!a.w){g.Mo("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+a.A.title);
a.H=(0,g.mq)();a.w=new g.I((0,g.x)(a.Tp,a,b),25);a.Tp(b);var c=b||g.R(a.u.O().experiments,"autoplay_time")||1E4;a.u.la("onAutonavCoundownStarted",c)}g.Gn(a.element,"ytp-upnext-autoplay-paused")},$4=function(a){Z4(a);
a.H=(0,g.mq)();a.Tp();g.J(a.element,"ytp-upnext-autoplay-paused")},Z4=function(a){a.w&&(a.w.dispose(),a.w=null)},a5=function(a,b){b=void 0===b?!1:b;
if(g.Q(a.u.O().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.xa(),a.Jm(),a.C=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:c.title,icon:c.xc()}),a.F=a.L(a.C,"click",a.FL),a.G.start())}Z4(a);a.u.nextVideo(!1,b)},b5=function(a,b){g.U.call(this,{D:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},dsa=function(a){b5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.U({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",M:{src:b.Ld}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",V:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.B(this,this.u);this.u.ca(this.element);this.subscribeButton=new g.cQ("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",null,
!0,!1,b.qg,b.subscribed,"trailer-endscreen",null,null,a);g.B(this,this.subscribeButton);this.subscribeButton.ca(this.u.o["html5-subscribe-button-container"]);this.hide()},c5=function(a){var b=a.O(),c=g.Cv||g.sh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.U.call(this,{D:"a",W:e,M:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",M:c,K:[{D:"span",I:"ytp-videowall-still-info-title",V:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",V:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{D:"span",I:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{D:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",V:"{{playlist_length}}"},")"]}]},{D:"span",W:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{D:"span",I:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.suggestion=null;this.w=d;this.api=a;this.u=new g.O(this);g.B(this,this.u);this.ha("click",this.onClick);this.ha("keypress",this.B);this.u.L(a,"videodatachange",this.A);g.HL(a,this.element,this);this.A()},esa=function(a){var b=a.suggestion.xa().videoId,c=a.suggestion.getPlaylistId();
(g.uT(a.api.app,b,a.suggestion.Ob,c,void 0,void 0)||a.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.JL(a.api,a.element)},d5=function(a){b5.call(this,a,"videowall-endscreen");
var b=this;this.ba=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.O(this);g.B(this,this.w);this.F=new g.I(function(){g.J(b.element,"ytp-show-tiles")},0);
g.B(this,this.F);var c=new g.U({D:"button",W:["ytp-button","ytp-endscreen-previous"],M:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},K:[g.bM()]});g.B(this,c);c.ca(this.element);c.ha("click",this.QG,this);this.table=new g.wC({D:"div",I:"ytp-endscreen-content"});g.B(this,this.table);this.table.ca(this.element);c=new g.U({D:"button",W:["ytp-button","ytp-endscreen-next"],M:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},K:[g.cM()]});g.B(this,c);c.ca(this.element);c.ha("click",
this.PG,this);this.u=new X4(a);g.B(this,this.u);g.EL(this.player,this.u.element,4);this.hide()},e5=function(a){return g.FL(a.player)&&a.Hv()&&!a.B},fsa=function(a,b){return(0,g.Fc)(b.suggestions,function(c){c=g.DN(a.ba.O(),c);
g.B(a,c);return c})},f5=function(a){var b=a.ks();
b!==a.H&&(a.H=b,a.player.R("autonavvisibility"))},g5=function(a){g.wP.call(this,a);
this.endScreen=null;this.listeners=new g.O(this);g.B(this,this.listeners);this.o=a.O();gsa(a)?this.endScreen=new d5(this.player):this.o.Ia?this.endScreen=new dsa(this.player):this.endScreen=new b5(this.player);g.B(this,this.endScreen);g.EL(this.player,this.endScreen.element,4);this.oB();this.listeners.L(a,"videodatachange",this.oB,this);this.listeners.L(a,g.QD("endscreen"),this.NG,this);this.listeners.L(a,"crx_endscreen",this.wK,this)},gsa=function(a){a=a.O();
return a.Ha&&!a.Ia};
g.r(X4,g.U);g.h=X4.prototype;g.h.Jm=function(){this.C&&(this.G.stop(),this.Xa(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.Uz=function(){g.AC(this,g.gL(this.u))};
g.h.FL=function(){window.focus();this.Jm()};
g.h.hide=function(){g.U.prototype.hide.call(this)};
g.h.Tp=function(a){a=a||g.R(this.u.O().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.mq)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?a5(this,!0):this.w&&this.w.start()};
g.h.OL=function(a){!g.Zd(this.B.element,g.Eq(a))&&g.JM(a,this.u)&&a5(this)};
g.h.eK=function(){g.iL(this.u,!0)};
g.h.gL=function(a){this.u.getPresentingPlayerType();this.show();Y4(this,a)};
g.h.oC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.xa().videoId==a.xa().videoId||(this.A=a,W4(this,a,"hqdefault.jpg"))};
g.h.hL=function(){this.u.getPresentingPlayerType();Z4(this);this.hide()};
g.h.X=function(){Z4(this);this.Jm();g.U.prototype.X.call(this)};g.r(b5,g.U);g.h=b5.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Hv=function(){return!1};
g.h.ks=function(){return!1};
g.h.Qx=function(){return!1};g.r(dsa,b5);g.r(c5,g.U);c5.prototype.onClick=function(a){g.JM(a,this.api,this.w,this.suggestion.Ob||void 0)&&esa(this)};
c5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.Jq(a)||(esa(this),g.Iq(a))}};
c5.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.O();this.w=a.pc?!1:b.u};g.r(d5,b5);g.h=d5.prototype;g.h.create=function(){b5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=fsa(this,a),this.videoData=a);this.mg();this.w.L(this.player,"appresize",this.mg);this.w.L(this.player,"onVideoAreaChange",this.mg);this.w.L(this.player,"videodatachange",this.SG);this.w.L(this.player,"autonavchange",this.ls);this.w.L(this.player,"autonavcancel",this.OG);a=this.videoData.autonavState;a!==this.G&&this.ls(a);this.w.L(this.element,"transitionend",this.eN)};
g.h.destroy=function(){g.rr(this.w);g.je(this.stills);this.stills=[];this.suggestions=null;b5.prototype.destroy.call(this);g.Gn(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.Hv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){b5.prototype.show.call(this);g.Gn(this.element,"ytp-show-tiles");this.player.O().o?g.wn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.iL(this.player,!1);e5(this)?(f5(this),2===this.videoData.autonavState?g.Q(this.player.O().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?a5(this.u,!0):Y4(this.u):3===this.videoData.autonavState&&$4(this.u)):(g.iL(this.player,!0),f5(this))};
g.h.hide=function(){b5.prototype.hide.call(this);$4(this.u);f5(this)};
g.h.eN=function(a){g.Eq(a)===this.element&&this.mg()};
g.h.mg=function(){if(this.suggestions&&this.suggestions.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.vL(this.ba,!0,this.ba.isFullscreen()),b=g.RC(this.ba);b&&(b=b.dc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&z)n-=q*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.nd(a.width/m||1,1,1.21);n*=g.nd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Ih(a,m,n);g.ph(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;W4(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",e5(this));f5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),q=g.od(q+this.A,l),0!==t){u=this.stills[c];u||(u=new c5(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-z-4,G=Math.floor(m*(f+t)/b)-C-4;g.yh(u.element,C,z);g.Ih(u.element,G,D);g.ph(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1===t);g.K(u.element,"ytp-videowall-still-large",
2<t);t=u;q=this.suggestions[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.O(),z=g.En(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",W4(t,q,z),g.qx(u)&&(u=q.Eh(),u=g.ah(u,g.AD({},"emb_rel_end")),t.ga("url",u)),(q=(q=q.Ob)&&q.itct)&&g.IL(t.api,t.element,q));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Vd(e.element),g.ie(e);this.stills.length=c}};
g.h.SG=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=fsa(this,a),this.videoData=a,this.mg())};
g.h.PG=function(){this.A+=this.stills.length;this.mg()};
g.h.QG=function(){this.A-=this.stills.length;this.mg()};
g.h.Qx=function(){return!!this.u.w};
g.h.ls=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,Z4(this.u),this.Fa()&&this.mg()):(this.C=!0,this.Fa()&&e5(this)&&(2===a?Y4(this.u):3===a&&$4(this.u)))};
g.h.OG=function(a){if(a){for(a=0;a<this.stills.length;a++)g.KL(this.ba,this.stills[a].element,!0);this.ls(1)}else this.B=null,this.C=!1;this.mg()};
g.h.ks=function(){return this.Fa()&&e5(this)};g.r(g5,g.wP);g.h=g5.prototype;g.h.Fy=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!gsa(this.player)||b;var c=a.vi||g.zx(a.La),d=g.PS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Ey=function(){return this.endScreen.ks()};
g.h.DF=function(){return this.Ey()?this.endScreen.Qx():!1};
g.h.X=function(){g.NQ(this.player.app,"endscreen",void 0);g.wP.prototype.X.call(this)};
g.h.load=function(){g.wP.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.wP.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.NG=function(a){this.Fy()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.wK=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.oB=function(){g.NQ(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.ND(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.B(this,a);var b=new g.ND(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.B(this,b);g.AL(this.player,[a,b])};g.LP.endscreen=g5;})(_yt_player);
